### ISSUE TITLE
Hello World isn't working

### ISSUE THREAD

**Issue by Quantum10101** [blackboardsh/electrobun#10]
I am very excited about this project!

I attempted these steps two times just to be sure:
https://www.electrobun.dev/guides/hello-world

I am on Ubuntu 22.04 and tried with both Bun 1.1.20 and 1.1.24.

After following all the steps exactly, this is what happens when I run it:
```
$ bun start
$ bun run build:dev && electrobun dev
$ electrobun build
/usr/bin/bash: line 1: /home/quantum/electrobun-test/node_modules/.bin/electrobun: cannot execute binary file: Exec format error
error: script "build:dev" exited with code 126
error: script "start" exited with code 126
```

**Comment by YoavCodes** [comment]
Currently Electrobun only supports building on arm mac and distributing to arm mac. 

Linux and Windows support (as build targets and separately as development environments) are on the roadmap.

You can see the compatibility table here: https://www.electrobun.dev/docs/guides/Compatability

semi-related-update: the hello world link is now at https://www.electrobun.dev/docs/guides/Getting%20Started/Hello%20World

I'm gonna close this issue, and will create a new one later when we get there in the roadmap
