### ISSUE TITLE
Menu component does not work in ElectroBun environment.

### ISSUE THREAD

**Issue by janckerchen** [blackboardsh/electrobun#26]
The following code works fine in the browser environment, but does not work in the ElectroBun environment.

```jsx
import {Provider} from '@/components/ui/provider'
import {
  MenuContent,
  MenuItem,
  MenuRoot,
  MenuTrigger,
} from '@/components/ui/menu'
import {Button} from '@/components/ui/button'

export const App = () => (
  <Provider>
    <MenuRoot>
      <MenuTrigger asChild>
        <Button variant='outline' size='sm'>
          Open
        </Button>
      </MenuTrigger>
      <MenuContent>
        <MenuItem value='new-txt'>New Text File</MenuItem>
        <MenuItem value='new-file'>New File...</MenuItem>
        <MenuItem value='new-win'>New Window</MenuItem>
        <MenuItem value='open-file'>Open File...</MenuItem>
        <MenuItem value='export'>Export</MenuItem>
      </MenuContent>
    </MenuRoot>
  </Provider>

)
```

system environment

```
bun  1.1.33
"electrobun": "^0.0.15",
"@chakra-ui/react": "^3.0.2",
```

Error

<img width="583" alt="image" src="https://github.com/user-attachments/assets/e96a6655-695b-42eb-aa32-bde0026abdcc">

**Comment by YoavCodes** [comment]
Would be helpful for you to create a minimal repro and share a zip file or github project with it.

i suspect this is either:
- a chakra-ui issue in webkit (you can test in safari)
- a chakra-ui issue with bun build (maybe only compatible with vite or webpack)
- a chakra-ui or general React bug in your actual code

I’ve heard of chakra-ui issues when the bundler doesn’t handle cyclical imports in a certain way.

**Comment by janckerchen** [comment]
I have submitted  [the  issue](https://github.com/chakra-ui/chakra-ui/issues/9072) to chakra-ui.
