### ISSUE TITLE
Ready for side projects?

### ISSUE THREAD

**Issue by forresto** [blackboardsh/electrobun#7]
It's cool to see your progress here! Should I tinker with it or wait a little bit?

**Comment by forresto** [comment]
I've been using Safari's "Add to Dock" for all of my most-used web apps. G Photos, G Mail, Discord, Notion, Cuttle. 

Maybe a cool demo would be local-first, and use the local filesystem. Markdown editor? That would be kinda like [Obsidian](https://obsidian.md).

**Comment by YoavCodes** [comment]
> Should I tinker with it or wait a little bit?

I'm working on the docs site and publishing to npm. probably best to wait till then. coming soonish.

I've already ported co(lab) from electron to electrobun which is a relatively complex **hybrid browser + code editor** app, re-launching soon. Debating if I should open source that or not.

The Playground app (in the repo now) is kind of a mess at the moment, it does/demos tons of stuff but probably only if you know what to look for in the terminal. Will be cleaning it up to be a proper intro Playground app so it becomes a QA tool and nice interactive demo of all the apis.

**Comment by YoavCodes** [comment]
Just put up a new docs site here: https://www.electrobun.dev/ with a few guides and api docs.

Currently supports building on and distributing to arm mac.
